version: '3.7'
services:
  app:
    build: &app-build
      context: .
      dockerfile: deploy/components/app/workspace.Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    volumes: &app-volumes
      - ./:/code
      - ./deploy/components/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend
    depends_on:
      - worker
      - redis

  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/code:delegated
      - ./deploy/components/server/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:delegated
    networks:
      - backend
    depends_on:
      - app

  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    ports:
      - 6382:6379
    networks:
      - backend

  worker:
    build: *app-build
    container_name: worker
    entrypoint: php artisan queue:work
    restart: unless-stopped
    tty: true
    volumes: *app-volumes
    networks:
      - backend
    depends_on:
      - redis

networks:
  backend:
    driver: bridge