version: '3.7'
services:
  app:
    image: &app-image ghcr.io/debeule/versioning-api/app:latest
    build:
      context: .
      dockerfile: deploy/components/app/workspace.Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    volumes: &app-volumes
      - ./:/code:delegated
      - ./deploy/components/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend
    depends_on:
      - db
      - db-testing
      - worker
      - redis

  server:
    image: nginx:alpine
    container_name: server
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/code:delegated
      - ./deploy/components/server/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf:delegated
    networks:
      - backend
    depends_on:
      - app

  db:
    image: &db-image mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment: &db-environment
      MYSQL_DATABASE: sport-na-school
      MYSQL_ROOT_PASSWORD: sport-na-school
      MYSQL_ROOT_HOST: '%'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  db-testing:
    image: *db-image
    container_name: db-testing
    restart: unless-stopped
    environment: *db-environment
    tty: true
    ports:
      - 3307:3306
    volumes:
      - dbdata-testing:/var/lib/mysql
    networks:
      - backend

  cron:
    image: ghcr.io/debeule/versioning-api/cron:latest
    build:
      context: .
      dockerfile: deploy/components/cron/workspace.Dockerfile
    container_name: cron
    restart: unless-stopped
    volumes: *app-volumes
    tty: true
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - backend

  worker:
    image: *app-image
    container_name: worker
    entrypoint: php artisan queue:work --timeout=300
    restart:  unless-stopped
    tty: true
    volumes: *app-volumes
    networks:
      - backend
    depends_on:
      - db
      - db-testing
      - redis

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
    driver: local
  dbdata-testing:
    driver: local