name: Build and deploy images

on:
  push:
    paths:
      - 'docker-compose.yml'
      - 'deploy/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'docker-compose.yml'
      - 'deploy/**'
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build app image
        run: docker compose build app

      
      - name: Build cron image
        run: docker compose build cron

      - name: Install composer dependencies in app image
        run: sudo docker exec -u 0 app composer install

      - name: Push images to GHCR
        run: docker compose push
      