name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: build containers
      run: docker compose up -d --wait

    - name: setup databases
      run: |
        sudo docker exec -u 0 app composer start
        sudo docker exec -u 0 app composer testing

    - name: add permissions to phpunit executable
      run: sudo docker exec -u 0 app chmod 777 vendor/bin/phpunit
        
    - name: Execute tests - PHPUnit
      run: sudo docker exec -u 0 app vendor/bin/phpunit
      